// Generated by tools/build-catalog.mjs. Every BFV weapon and map, for the Weapons and Maps tabs.
window.CATALOG = {
 "builtAt": "2026-10-02T23:34:08.855Z",
 "weapons": [
  {
   "name": "12g Automatic",
   "type": "Shotgun",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/67/68/12gAutomatic-4344bfef.png"
  },
  {
   "name": "Ag m/42",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/123/17/M42-7befb739.png"
  },
  {
   "name": "Ammo Crate",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/64/80/Supply_Ammo_Crate-40503eb3.png"
  },
  {
   "name": "Anti-Tank Bundle Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/114/1/Grenade_AntiTank_Frag_Impact-8e011bdd.png"
  },
  {
   "name": "AP Mine",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/63/67/Deployable_S35_SMine_Frag-c143b376.png"
  },
  {
   "name": "Arditi Dagger",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/40/125/ArditiDagger-2883ed9b.png"
  },
  {
   "name": "AT Grenade Pistol",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/121/56/Launcher_AntiTank_Pistol_Frag-7938b179.png"
  },
  {
   "name": "AT Mine",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/75/14/Deployable_AT_Mine-4bf207e1.png"
  },
  {
   "name": "Bandages",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/29/72/Supply_Medical_Pouch-1db89f38.png"
  },
  {
   "name": "BAR M1918A2",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/76/79/Bar1918_A2-b44ff667.png"
  },
  {
   "name": "Barbed Baseball Bat",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/3/9/BarbedBaseballBat-fdf73eab.png"
  },
  {
   "name": "Bolo-Guna",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/84/32/BoloKnife-5420b66c.png"
  },
  {
   "name": "Bone Saw",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/33/16/BoneSaw-df104409.png"
  },
  {
   "name": "Boys AT Rifle",
   "type": "Anti-materiel rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/40/8/BoysAT-d8f83999.png"
  },
  {
   "name": "Breda M1935 PG",
   "type": "Assault rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/96/128/BredaPG-a080089a.png"
  },
  {
   "name": "Bren Gun",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/76/39/BRENGun-4c2753f2.png"
  },
  {
   "name": "British Army Jack Knife",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/58/98/BritishArmyJackKnife-c6623eae.png"
  },
  {
   "name": "Broken Bottle",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/84/42/BrokenBottle-542adc4d.png"
  },
  {
   "name": "Burned Plank",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/17/45/BurnedPlank-112da8c0.png"
  },
  {
   "name": "Chauchat",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/16/54/Chauchat-10361a12.png"
  },
  {
   "name": "Club",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/65/50/MeleeClub-41ce6631.png"
  },
  {
   "name": "Combat Knife",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/126/72/KABARKnife-7e48ad8b.png"
  },
  {
   "name": "Commando Carbine",
   "type": "Bolt action carbine",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/24/90/DeLisleCarabine-18a64a00.png"
  },
  {
   "name": "Commando Machete",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/42/97/OkinawaMachete-d66152d3.png"
  },
  {
   "name": "Control Stick",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/25/102/JapaneseFlightStick-199a01ec.png"
  },
  {
   "name": "Coupe Coupe",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/96/115/CoupeCoupe-a08d5ff6.png"
  },
  {
   "name": "Cricket Bat",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/79/112/CricketBat-b1907335.png"
  },
  {
   "name": "Demolition Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/79/87/Grenade_Demolition-b1577ee3.png"
  },
  {
   "name": "Doppel-Schuss",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/41/125/Intel_DoubleBarrelFlareGun-d783a371.png"
  },
  {
   "name": "EGW Survival Knife",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/124/108/RustyEGWSurvivalKnife-846cfb4d.png"
  },
  {
   "name": "EMP",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/95/50/EMP-5f3287c2.png"
  },
  {
   "name": "Escape Axe",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/14/24/EscapeAxe-f2181991.png"
  },
  {
   "name": "Fallschirmjäger Switchblade",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/16/53/Switchblade-f03546ee.png"
  },
  {
   "name": "FG-42",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/58/56/FG42-c6c82ba2.png"
  },
  {
   "name": "Fire Axe",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/79/23/FireAxe-4f17c94d.png"
  },
  {
   "name": "Firecrackers",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/80/27/Throwable_M80-b0e5f292.png"
  },
  {
   "name": "Flare Gun",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/39/101/Intel_FlareGun-d99b0424.png"
  },
  {
   "name": "Fliegerfaust",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/78/82/Launcher_AntiAir_Rocket_Frag-b252fba3.png"
  },
  {
   "name": "Frag Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/81/102/Grenade_AntiPersonal_Frag_Fuse_UK-51667306.png"
  },
  {
   "name": "Frag Grenade Rifle",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/27/32/Launcher_SMLE_Grenade-1be05d77.png"
  },
  {
   "name": "German Naval Dagger",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/51/62/GermanNavalDagger-cdc209da.png"
  },
  {
   "name": "Gewehr 1-5",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/104/113/Gewehr15-688f09a9.png"
  },
  {
   "name": "Gewehr 43",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/53/116/Gewehr43-cb742d1a.png"
  },
  {
   "name": "Gewehr M95/30",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/50/Gewehr9530-e1ce76f9.png"
  },
  {
   "name": "Golden Eagle",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/51/55/GoldenEagleKnife-33c9216a.png"
  },
  {
   "name": "Hachiwari",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/91/11/Hachiwari-a5f5884a.png"
  },
  {
   "name": "Hatchet",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/115/91/Hatchet-8da526ed.png"
  },
  {
   "name": "Ilse's Pickaxe",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/23/65/Pickaxe-17bf1b74.png"
  },
  {
   "name": "Impact Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/79/127/Grenade_AntiPersonal_Frag_Impact_UK-4f81ac0f.png"
  },
  {
   "name": "Incendiary Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/59/68/Grenade_AntiPersonal_Fire-3bbc4243.png"
  },
  {
   "name": "Jungle Carbine",
   "type": "Bolt action carbine",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/48/99/LeeEinfeldNo5-309d1cbe.png"
  },
  {
   "name": "K31/43",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/111/12/K3143-910cfbf7.png"
  },
  {
   "name": "K98 Bayonet",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/61/90/K98Bayonet-3d5a1a9a.png"
  },
  {
   "name": "Kampfpistole",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/63/9/Launcher_AntiTank_Pistol_CMP-3f090ca4.png"
  },
  {
   "name": "Kar98k",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/1/45/Kar98K-01d381cd.png"
  },
  {
   "name": "Karabin 1938M",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/1/72/Wz38M-01b8c70d.png"
  },
  {
   "name": "Katana",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/39/62/Katana-273e8e24.png"
  },
  {
   "name": "KE7",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/118/90/SIGKE7-8aa6fea9.png"
  },
  {
   "name": "Knuckle Duster",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/88/13/USTrenchKnife-a80da6fb.png"
  },
  {
   "name": "Krag–Jørgensen",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/48/119/KragJorgensen-30895eb5.png"
  },
  {
   "name": "Kukri",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/99/51/Kukri-63cd4e8e.png"
  },
  {
   "name": "Kunai",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/106/16/Throwable_Kunai-9610d695.png"
  },
  {
   "name": "Lee-Enfield No.4 Mk I",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/123/1/LeeEnfield-85ff8090.png"
  },
  {
   "name": "Lever Pipe",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/49/11/LeverPipe-310bcfe7.png"
  },
  {
   "name": "Lewis Gun",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/32/48/LewisLMG-e0d04932.png"
  },
  {
   "name": "Liberator",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/14/107/FP45Liberator-0e952d0b.png"
  },
  {
   "name": "Lion Head Sword",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/78/85/Saber-4e5571ac.png"
  },
  {
   "name": "LS/26",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/63/120/LS26-c1883823.png"
  },
  {
   "name": "Lunge Mine",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/104/71/Boomstick-68475909.png"
  },
  {
   "name": "M1 Garand",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/62/43/M1Garand-3e2b5802.png"
  },
  {
   "name": "M1897",
   "type": "Shotgun",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/56/21/M1897Shotgun-381578b2.png"
  },
  {
   "name": "M1907 SF",
   "type": "Assault rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/10/84/M1907SF-f6ac6f26.png"
  },
  {
   "name": "M1911",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/15/46/M1911-0fd23c61.png"
  },
  {
   "name": "M1911 Suppressed",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/22/6/M1911_suppressed-ea0651d2.png"
  },
  {
   "name": "M1919A6",
   "type": "Mmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/78/45/M1919A6-b22db6be.png"
  },
  {
   "name": "M1922 MG",
   "type": "Mmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/13/91/Darne-f35be432.png"
  },
  {
   "name": "M1928A1",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/61/31/Thompson-c31f1ac0.png"
  },
  {
   "name": "M1941 Johnson",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/55/71/M1941_JohnsonRifle-374730d3.png"
  },
  {
   "name": "M1A1 Bazooka",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/120/61/Launcher_AntiTank_Rocket_Frag_04-883dd48a.png"
  },
  {
   "name": "M1A1 Carbine",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/14/114/M1A1Carbine-0e72e354.png"
  },
  {
   "name": "M2 Carbine",
   "type": "Assault rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/42/42/M2Carbine-d6d6efcb.png"
  },
  {
   "name": "M2 Flamethrower",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/86/101/Flamethrower_M2-aa650aed.png"
  },
  {
   "name": "M28 con Tromboncino",
   "type": "Bolt action carbine",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/101/Tromboncino_M28-e19b76f7.png"
  },
  {
   "name": "M3 Grease Gun",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/108/75/M3SMG-6cb56d9d.png"
  },
  {
   "name": "M3 Infrared",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/93/6/M3_Infrared_SniperCarbine-a3fa218b.png"
  },
  {
   "name": "M30 Drilling",
   "type": "Shotgun",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/109/46/M30LuftwaffeDrilling-93d25c9c.png"
  },
  {
   "name": "MAB 38",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/89/MAB38-e1595a2e.png"
  },
  {
   "name": "Madsen MG",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/72/30/MiniMadsen-b8e2e5c4.png"
  },
  {
   "name": "MAS 44",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/112/118/Mas44-70764a58.png"
  },
  {
   "name": "Medical Crate",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/BfvBeta/77/14/Supply_Medical_Crate-b3f2f42a.png"
  },
  {
   "name": "Medical Syringe",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/82/25/Supply_Medical_Syringe-aee7e9fa.png"
  },
  {
   "name": "MG 34",
   "type": "Mmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/12/71/MG34-f447ad5e.png"
  },
  {
   "name": "MG 42",
   "type": "Mmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/28/90/MG42-1ca6b52d.png"
  },
  {
   "name": "Mk VI Revolver",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/104/47/MKVIRevolver-982f4b4b.png"
  },
  {
   "name": "MKIII(S) Elite Combat Dagger",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/118/108/FirestormKnife-8a6cc848.png"
  },
  {
   "name": "Model 27",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/74/62/Model27_Long-4a3efef6.png"
  },
  {
   "name": "Model 37",
   "type": "Shotgun",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/30/81/Model37-e2aff9bb.png"
  },
  {
   "name": "Model 8",
   "type": "Self-loading rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/16/90/RemingtonM8-10a6aa82.png"
  },
  {
   "name": "MP28",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/16/100/MP28-f09c5670.png"
  },
  {
   "name": "MP34",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/126/28/MP34-82e44afe.png"
  },
  {
   "name": "MP40",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/1/100/MP40-0164787e.png"
  },
  {
   "name": "P08 Carbine",
   "type": "Pistol carbine",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/92/106/P08Carbine-5c6a750b.png"
  },
  {
   "name": "P08 Pistol",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/20/62/LugerP8-ec3e2eca.png"
  },
  {
   "name": "P38 Pistol",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/56/19/WaltherP38-3813c59d.png"
  },
  {
   "name": "Panzerbüchse 39",
   "type": "Anti-materiel rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/86/77/Panzerbuchse_39-aab3bc76.png"
  },
  {
   "name": "Panzerfaust",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/5/34/Launcher_AntiTank_Rocket_Frag_01-05de7537.png"
  },
  {
   "name": "PIAT",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/72/110/Launchers_AntiTank_Rocket_Frag_03-b86e6998.png"
  },
  {
   "name": "Pickaxe",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/23/65/Pickaxe-17bf1b74.png"
  },
  {
   "name": "Pistol Flamethrower",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/123/106/Launcher_AntiPersonal_Pistol_Fire-859644ba.png"
  },
  {
   "name": "Poignard",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/56/38/Poignard-c8264c7b.png"
  },
  {
   "name": "PPK",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/101/40/WaltherPPK-6528d353.png"
  },
  {
   "name": "PPKS",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/72/67/WaltherPPKSuppressed-b8bdb5d5.png"
  },
  {
   "name": "Repetierpistole M1912",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/25/63/SteyrM1912-19c1c826.png"
  },
  {
   "name": "Ribeyrolles 1918",
   "type": "Assault rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/18/44/Ribeyrolles-eed41ed9.png"
  },
  {
   "name": "RMN50 Rifle Frag",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/100/46/Launcher_RMN_Grenade-9cd222df.png"
  },
  {
   "name": "Ross Rifle Mk III",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/55/48/RossRifle-c930c7e9.png"
  },
  {
   "name": "RSC",
   "type": "Self-loading rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/88/RSC-1f58be6c.png"
  },
  {
   "name": "Ruby",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/2/114/RubyPistol-02727dd8.png"
  },
  {
   "name": "S2-200",
   "type": "Mmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/42/122/S2200-d68665c9.png"
  },
  {
   "name": "Sai",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/89/111/IronSai-a7911f90.png"
  },
  {
   "name": "Scout Knife M1916",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/108/117/ScoutKnifeM1916-6c8b69f9.png"
  },
  {
   "name": "Selbstlader 1906",
   "type": "Self-loading rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/73/15/Selbstlader1906-b7f1cea4.png"
  },
  {
   "name": "Selbstlader 1916",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/11/36/Selbstlader1916-f5dcd71a.png"
  },
  {
   "name": "Shaped Charge",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/6/96/Deployable_AT_ShapedCharge-06a088be.png"
  },
  {
   "name": "Shovel",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/118/125/Shovel-767d811e.png"
  },
  {
   "name": "Sjögren Shotgun",
   "type": "Shotgun",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/67/49/SjogrenShotgun-43cfe31f.png"
  },
  {
   "name": "Smoke Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/21/11/Grenade_AntiPersonal_Smoke-150b5665.png"
  },
  {
   "name": "Smoke Grenade Rifle",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/27/32/Launcher_SMLE_Grenade-1be05d77.png"
  },
  {
   "name": "Sniper Decoy",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/127/117/Intel_SniperDecoy-818b3745.png"
  },
  {
   "name": "Solveig's Knife",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/103/52/SolveigKnife-9934570a.png"
  },
  {
   "name": "Spawn Beacon",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/14/64/Deployable_SpawnBeacon_Single-f2c0bc51.png"
  },
  {
   "name": "Spotting Scope",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/87/49/Intel_Scope-a931f9f1.png"
  },
  {
   "name": "STEN",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/111/56/STENGun-9138fc17.png"
  },
  {
   "name": "StG 44",
   "type": "Assault rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/105/84/STG44MP44-97548575.png"
  },
  {
   "name": "Sticky Dynamite",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/67/64/Deployable_Dynamite_Sticky-bdc0d316.png"
  },
  {
   "name": "Sticky Grenade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/63/128/Grenade_AntiTank_Frag_Sticky-3f809cbe.png"
  },
  {
   "name": "Sturmgewehr 1-5",
   "type": "Assault rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/92/116/SturmGewehr15-a4740184.png"
  },
  {
   "name": "Suomi KP/-31",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/43/8/Suomi-2bf82a33.png"
  },
  {
   "name": "The Unexpected Gift",
   "type": "Melee",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/93/106/ChristmasBaseballBat-a3965f86.png"
  },
  {
   "name": "Throwing Blade",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/10/68/Throwable_Blade-f644ba87.png"
  },
  {
   "name": "Trench Carbine",
   "type": "Pistol carbine",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/81/86/C96_Carbine-af56338e.png"
  },
  {
   "name": "Turner SMLE",
   "type": "Semi-auto rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/117/98/TurnerSMLE-75621421.png"
  },
  {
   "name": "Type 100",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/117/23/Type100_SMG-8b174d3a.png"
  },
  {
   "name": "Type 11 LMG",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/22/107/Nambu_Type11-166b8aa9.png"
  },
  {
   "name": "Type 2A",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/59/80/Nambu_Type2A-3b5090e2.png"
  },
  {
   "name": "Type 94",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/80/92/Type94_Pistol-50a47503.png"
  },
  {
   "name": "Type 97 MG",
   "type": "Lmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/1/74/Type97MG-01b69c34.png"
  },
  {
   "name": "Type 99 Arisaka",
   "type": "Bolt action rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/53/117/Type_99_Arisaka-cb8bc4ed.png"
  },
  {
   "name": "Type 99 Mine",
   "type": "Gadget",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/39/111/Deployable_Type99_Mine-d96f6efd.png"
  },
  {
   "name": "VGO",
   "type": "Mmg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/17/53/VickersK-11cb114e.png"
  },
  {
   "name": "Welgun",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/82/71/Welgun-aeb91d41.png"
  },
  {
   "name": "Welrod",
   "type": "Sidearm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/12/75/Welrod-f4b59480.png"
  },
  {
   "name": "ZH-29",
   "type": "Self-loading rifle",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/98/26/ZH29-62e6adf5.png"
  },
  {
   "name": "ZK-383",
   "type": "Smg",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/55/66/ZK383-374279ef.png"
  }
 ],
 "vehicles": [
  {
   "name": "40mm aa",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/111/83/Stationary_40mmAA-91ad1c10.png"
  },
  {
   "name": "6 pounder",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/87/113/QF6Pounder-a98f3167.png"
  },
  {
   "name": "A-20 bomber",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/59/57/A20-c5c7daa0.png"
  },
  {
   "name": "Bf 109 g-2",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/58/67/BF109-c6bd45c6.png"
  },
  {
   "name": "Bf 109 g-6",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/58/67/BF109-c6bd45c6.png"
  },
  {
   "name": "Blenheim mk if",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/84/16/blenheim-acf0c257.png"
  },
  {
   "name": "Blenheim mki",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/84/16/blenheim-acf0c257.png"
  },
  {
   "name": "C-47",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/84/88/C47-aca81f3d.png"
  },
  {
   "name": "Churchill crocodile",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/48/121/ChurchillCrocodileTank-d0878564.png"
  },
  {
   "name": "Churchill gun carrier",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/7/37/ChurchillGunCarrierTank-0725b8c6.png"
  },
  {
   "name": "Churchill mk vii",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/34/72/churchill_MKVII-22b8525d.png"
  },
  {
   "name": "Corsair f4u-1a",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/56/Pac_Corsair-1f38fce6.png"
  },
  {
   "name": "Corsair f4u-1c",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/56/Pac_Corsair-1f38fce6.png"
  },
  {
   "name": "Dinghy",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/119/34/Boat_Dinghy-7722932f.png"
  },
  {
   "name": "Fl 282 kolibri (s)",
   "type": "Helicopters",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/98/46/Vehicle_Blueprint_Helicopter-9ed2c846.png"
  },
  {
   "name": "Flak 38",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/69/7/FLAK38AA-45078234.png"
  },
  {
   "name": "Flakpanzer iv",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/44/0/PanzerIVWirbelwind-d40033e6.png"
  },
  {
   "name": "Gpw",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/114/43/Car_Willys-8ed5b812.png"
  },
  {
   "name": "Hachi",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/19/22/Chi-Ha_RocketLauncher_DeployVersion-13eacf14.png"
  },
  {
   "name": "Ju-88 a",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/58/34/JU88C-3a2296b6.png"
  },
  {
   "name": "Ju-88 c",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/83/65/JU88_C-ad411a79.png"
  },
  {
   "name": "Ka-mi",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/50/29/Pac_KaMi-321d1463.png"
  },
  {
   "name": "Kettenkrad",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/28/17/KettenkradLightTransport-1cefde85.png"
  },
  {
   "name": "Kübelwagen",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/60/54/KubelwagenTransport-c436e207.png"
  },
  {
   "name": "Lcvp",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/37/126/Boat_Higgins-257e601c.png"
  },
  {
   "name": "Lvt",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/1/124/Pac_LVT-0184b9e2.png"
  },
  {
   "name": "M2 hmg",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/3/61/Stationary_M2_HMG-fd3d7264.png"
  },
  {
   "name": "M3",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/93/64/M3-5dc0e0e7.png"
  },
  {
   "name": "M8 greyhound",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/118/71/Greyhound-76b96c18.png"
  },
  {
   "name": "Mosquito fb mkvi",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/41/114/Mosquito_FBMkVI-29722e50.png"
  },
  {
   "name": "Mosquito mkii",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/14/61/MosquitoFBMkVI-0e3d6935.png"
  },
  {
   "name": "P-70 night fighter",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/59/57/A20-c5c7daa0.png"
  },
  {
   "name": "P51d fighter",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/15/21/Mustang-0f157d3d.png"
  },
  {
   "name": "P51k fighter",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/15/21/Mustang-0f157d3d.png"
  },
  {
   "name": "Pak 40",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/57/61/PAK40-39c3918d.png"
  },
  {
   "name": "Panzer 38t",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/37/90/Panzer38t-255a0727.png"
  },
  {
   "name": "Panzer iv",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/83/59/PanzerIVTank_1-adc5c741.png"
  },
  {
   "name": "Pickup truck",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/28/20/Vehicle_Blueprint_PickUpTruck-1cec836a.png"
  },
  {
   "name": "Schwimmwagen",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/64/2/Vehicle_Blueprint_Schimmwagon-c0fe4bd2.png"
  },
  {
   "name": "Sd. kfz 251 halftrack",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/8/108/HanomagHalftrack-f86c7ef0.png"
  },
  {
   "name": "Sd. kfz. 251 pakwagen",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/23/24/PakwagenHalftrack-17e871af.png"
  },
  {
   "name": "Sdkfz 234 puma",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/104/24/Puma-68e8c940.png"
  },
  {
   "name": "Sherman",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/62/59/Pac_Sherman-c2c53239.png"
  },
  {
   "name": "Spitfire mk va",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/80/12/SpitfirePlane_MX-Va-b00c8a23.png"
  },
  {
   "name": "Spitfire mk vb",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/80/12/SpitfirePlane_MX-Va-b00c8a23.png"
  },
  {
   "name": "Sports car",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/103/47/Vehicle_Blueprint_SportsCar-992f5dbd.png"
  },
  {
   "name": "Staff car",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/111/6/Vehicle_Blueprint_StaffCar-6f06976a.png"
  },
  {
   "name": "Staghound t17e1",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/86/30/staghound-aae207df.png"
  },
  {
   "name": "Stationary mg34",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/13/124/MG34_Stationary-0d84725f.png"
  },
  {
   "name": "Stuka b-1",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/72/103/Stuka_JU-87_B-1-b8672113.png"
  },
  {
   "name": "Stuka b-2",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/32/46/Stuka_JU-87_B-2-e0d2ffbf.png"
  },
  {
   "name": "Sturmgeschutz iv",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/19/60/StugIV-133ce60b.png"
  },
  {
   "name": "Sturmtiger",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/60/118/Sturmtiger-3c762491.png"
  },
  {
   "name": "T34 calliope",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/24/64/Sherman_Calliope_DeployVersion-18400eba.png"
  },
  {
   "name": "T48 gmc",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/27/54/M3_T48-1bcaca18.png"
  },
  {
   "name": "Tiger i",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/119/57/tiger-89c7d89c.png"
  },
  {
   "name": "Tractor",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/56/26/Vehicle_Blueprint_Tractor-38e6f5df.png"
  },
  {
   "name": "Type 10",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/81/86/Stationary_Type10-5156b60a.png"
  },
  {
   "name": "Type 93 hmg",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/16/23/Stationary_Type92_HMG-10e95b63.png"
  },
  {
   "name": "Type 95 car",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/125/47/Car_Type95_Kurogane-832fd07e.png"
  },
  {
   "name": "Type 97",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/79/98/Pac_ChiHa-4f62188f.png"
  },
  {
   "name": "Universal carrier",
   "type": "Transports",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/31/11/UniversalCarrier-e1f57b59.png"
  },
  {
   "name": "Valentine aa mk i",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/9/61/ValentineCrusaderAA-f7c31668.png"
  },
  {
   "name": "Valentine archer",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/109/49/ArcherTankDestroyer-93312d76.png"
  },
  {
   "name": "Valentine mk viii",
   "type": "Tanks",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/40/55/valentine-2837c094.png"
  },
  {
   "name": "Vickers",
   "type": "Stationary",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/21/95/VickersStationaryMG-eb5f1bdb.png"
  },
  {
   "name": "Zero a6m2",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/50/12/Pac_Zero-32f4d600.png"
  },
  {
   "name": "Zero a6m5",
   "type": "Planes",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/50/12/Pac_Zero-32f4d600.png"
  }
 ],
 "maps": [
  {
   "name": "Aerodrome",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/118/45/1080p_MP_AfricanFox-8ad380a5.jpg"
  },
  {
   "name": "Al Marj Encampment",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/67/84/1080p_MP_Libya-bd54b090.jpg"
  },
  {
   "name": "Al Sundan",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/16/113/1080p_MP_SandAndSea-f071e6f7.jpg"
  },
  {
   "name": "Arras",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/75/97/1080p_MP_Arras-4b610505.jpg"
  },
  {
   "name": "Devastation",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/98/61/1080p_MP_Devastation-623dea60.jpg"
  },
  {
   "name": "Fjell 652",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/33/60/1080p_MP_ArcticFjell-df3c1290.jpg"
  },
  {
   "name": "Halvøy",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/93/61/DK_Norway_1080p-5d3d58c1.jpg"
  },
  {
   "name": "Hamada",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/49/22/1080p_MP_AfricanHalfaya-31165f9b.jpg"
  },
  {
   "name": "Iwo Jima",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/118/8/1080p_MP_IwoJima-760850fc.jpg"
  },
  {
   "name": "Lofoten Islands",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/125/109/1080p_MP_Norway-7d6d6300.jpg"
  },
  {
   "name": "Marita",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/58/76/1080p_MP_Kalamas-c64c8451.jpg"
  },
  {
   "name": "Mercury",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/48/74/1080p_MP_Crete-304a202d.jpg"
  },
  {
   "name": "Narvik",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/123/94/1080p_MP_ArcticFjord-7ba29138.jpg"
  },
  {
   "name": "Operation Underground",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/123/81/1080p_MP_Bunker-7b518876.jpg"
  },
  {
   "name": "Pacific Storm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/98/10/1080p_MP_TropicIslands-9e0a41c3.jpg"
  },
  {
   "name": "Panzerstorm",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/21/66/1080p_MP_Hannut-ebbe7197.jpg"
  },
  {
   "name": "Provence",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/87/80/1080p_MP_ProvenceXL-a950ad3e.jpg"
  },
  {
   "name": "Rotterdam",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/85/99/1080p_MP_Rotterdam-55632240.jpg"
  },
  {
   "name": "Solomon Islands",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/113/66/1080p_MP_Jungle-714218ce.jpg"
  },
  {
   "name": "Twisted Steel",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/105/100/1080p_MP_Escaut-9764d1fb.jpg"
  },
  {
   "name": "Wake Island",
   "image": "https://eaassets-a.akamaihd.net/battlelog/battlebinary/gamedata/Casablanca/50/56/1080p_MP_WakeIsland-3238b455.jpg"
  }
 ]
};
