// Builds catalog.js: every BFV weapon, vehicle and map, with images, for those tabs.
//
// gametools has no "all weapons" endpoint and each player's profile only lists some of them, so
// the weapon list is the union across the oul roster. Maps come from live server rotations.
//
//   node tools/build-catalog.mjs

import { writeFileSync } from "node:fs";

const API = "https://api.gametools.network";
const PLATOON_ID = "c46223f9-6b15-4977-9533-f74717125873";

const get = async (path) => {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(`${API}${path}`, { signal: AbortSignal.timeout(30000) });
      if (res.ok) return await res.json();
    } catch {}
  }
  return null;
};

const mapLimit = async (items, limit, fn) => {
  let i = 0;
  await Promise.all(Array.from({ length: limit }, async () => {
    while (i < items.length) await fn(items[i++]);
  }));
};

// Weapons
const roster = await get(`/bfglobal/detailedplatoon/?id=${PLATOON_ID}&platform=pc`);
const ids = [...roster.members.map((m) => m.id), "1009383862001", "1010338674560"];
const weapons = new Map();
const vehicles = new Map();
let done = 0;
await mapLimit(ids, 6, async (id) => {
  const p = await get(`/bfv/all/?playerid=${id}&platform=pc&skip_battlelog=true&format_values=false&lang=en-us`);
  for (const w of p?.weapons || []) {
    if (!weapons.has(w.weaponName)) weapons.set(w.weaponName, { name: w.weaponName, type: w.type, image: w.image });
  }
  for (const v of p?.vehicles || []) {
    if (!vehicles.has(v.vehicleName)) vehicles.set(v.vehicleName, { name: v.vehicleName, type: v.type, image: v.image });
  }
  process.stdout.write(`\rprofiles ${++done}/${ids.length}, weapons ${weapons.size}, vehicles ${vehicles.size}`);
});
console.log();

// Maps
const maps = new Map();
const { servers } = await get(`/bfv/servers/?name=&platform=pc&limit=250&region=all`);
for (const s of servers) if (s.currentMap && s.url) maps.set(s.currentMap, s.url);
await mapLimit(servers, 8, async (s) => {
  const d = await get(`/bfv/detailedserver/?gameid=${s.gameId}&platform=pc&lang=en-us`);
  for (const m of d?.rotation || []) if (m.mapname && m.image && !maps.has(m.mapname)) maps.set(m.mapname, m.image);
});

const byName = (a, b) => a.name.localeCompare(b.name);
const catalog = {
  builtAt: new Date().toISOString(),
  weapons: [...weapons.values()].sort(byName),
  vehicles: [...vehicles.values()].sort(byName),
  maps: [...maps].map(([name, image]) => ({ name, image })).sort(byName),
};
// A script rather than JSON: pages opened straight from disk (file://) can't fetch() local files,
// but they can load a <script>.
writeFileSync(
  new URL("../catalog.js", import.meta.url),
  `// Generated by tools/build-catalog.mjs. Every BFV weapon and map, for the Weapons and Maps tabs.\n` +
    `window.CATALOG = ${JSON.stringify(catalog, null, 1)};\n`,
);
console.log(`catalog.js: ${catalog.weapons.length} weapons, ${catalog.vehicles.length} vehicles, ${catalog.maps.length} maps`);
